# This is a basic workflow to help you get started with Actions

name: CI-CD-Pipeline-to-AWS-Elastic-BeansTalk
env:
  EB_PACKAGE_S3_BUCKET_NAME : "adv-it-flask-application-packages2"
  EB_APPLICATION_NAME       : "MyFlask"
  EB_ENVIRONMENT_NAME       : "MyFlask-env"
  DEPLOY_PACKAGE_NAME       : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-2"


on:
  push:
    branches: 
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest
      
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
      - name: Create zip deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
